name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cwd
        run: pwd
      - name: Docker compose
        run: docker compose up -d
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
      - name: Test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true # Allows the next step to reuse cache
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: app
